---
apiVersion: v1
kind: Template
metadata:
  name: deployment-config-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        name: ${APP_NAME}
      strategy:
        type: Rolling
        rollingParams:
      template:
        metadata:
          labels:
            name: ${APP_NAME}
        spec:
          containers:
            - name: kieserver
              imagePullPolicy: Always
              image: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/${SERVICE}:${IMAGE_VERSION}
              volumeMounts:
                # - name: spring-config
                #   mountPath: /deployments/application.properties
                #   readOnly: true
                #   subPath: application.properties
                - name: jta-pvc
                  mountPath: /opt/app/target/transaction-logs
                  readOnly: false
                - name: h2-pvc
                  mountPath: /opt/app/target/db
                  readOnly: false
#              env:
#                - name: JAVA_OPTIONS
#                  value: "-Dspring.profiles.active=local -Dorg.kie.server.startup.strategy=LocalContainersStartupStrategy -Dorg.kie.server.controller=ws://jbpm-console-new-hire:8080/websocket/controller -Dorg.kie.server.controller.user=user -Dorg.kie.server.controller.password=user -Dorg.kie.server.id=itorders -Dorg.kie.server.location=http://new-hire-service:8090/rest/server -Dkie.maven.offline.force=true -Dkie.maven.settings.custom=/tmp/maven/repository/settings.xml -Dorg.guvnor.m2repo.dir=/tmp/maven/repository"
              #   - name: SPRING_CONFIG_LOCATION
              #     value: /deployments/application.properties
          volumes:
            # - name: spring-config
            #   configMap:
            #     name: data-service-configmap
            #     defaultMode: 440
            #     items:
            #       - key: application.properties
            #         path: application.properties
            - name: jta-pvc
              defaultMode: 660
            - name: h2-pvc
              defaultMode: 660
          imagePullSecrets:
            - name: artifactory-puller
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${APP_NAME}-jta
      labels:
        app: ${APP_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${APP_NAME}-h2
      labels:
        app: ${APP_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi


parameters:
  - name: NAMESPACE
    displayName: Openshift namespace (project)
    description: Openshift namespace (project) this application resides in
    required: true
  - name: IMAGE_NAMESPACE
    displayName: Docker image namespace
    description: The docker namespace that the image belongs to
    required: true
  - name: IMAGE_VERSION
    displayName: Image Version
    description: Docker image version
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name